# Generated by Django 5.2 on 2025-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0002_document_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
