# Generated by Django 5.2 on 2025-05-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.TextField(default='#3788d8'),
        ),
    ]
