# Generated by Django 5.2.1 on 2025-05-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0006_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=100)),
                ('embed_html', models.TextField()),
                ('added_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
