# Generated by Django 5.2.1 on 2025-05-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0017_message_seen_message_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='provider',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='embed',
            name='title',
            field=models.CharField(),
        ),
    ]
