# Generated by Django 5.2.1 on 2025-05-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0019_whiteboard_stroke'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
