# Generated by Django 5.2.1 on 2025-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0020_whiteboard_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(),
        ),
    ]
