# Generated by Django 5.2.1 on 2025-06-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0022_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
