# Generated by Django 5.2.1 on 2025-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0023_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorage',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
