# Generated by Django 5.2.1 on 2025-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0025_message_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboard',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
