# Generated by Django 5.2.1 on 2025-06-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0028_webarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='webarchive',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
