# Generated by Django 5.2.1 on 2025-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0029_alter_webarchive_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webarchive',
            name='content',
            field=models.TextField(),
        ),
    ]
