# Generated by Django 5.2.1 on 2025-06-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0030_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
