# Generated by Django 5.2.1 on 2025-06-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eversyncc', '0031_event_recurrence_event_recurrence_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
